/*
 * By: Cobey Kromer
 * Date: 4/16/23
 * For: Controller class for actions taken by employees
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using GROUP9Project.DataBase;

namespace GROUP9Project.Controllers
{
    public static class EmployeeManager
    {
        // Returns the specified flights the accountant wants to look at
        public static List<Flight> FlightsForAccountant(DateTime date1, DateTime date2)
        {
            List<Flight> flights = ApplicationData.Connection.GetFlights();

            foreach (Flight flight in flights)
            {
                if(flight.FlightDate > date1 || flight.FlightDate < date2)
                    flights.Remove(flight);
            }
            return flights; 
        }

        // Returns a list of the specific incomes generated by each flight
        public static List<uint> IncomeOfFlights(List<Flight> flights)
        {
            List<uint> income = new List<uint>();
            List<BookingRecord> bookingRecords = new List<BookingRecord>();
            foreach (Flight flight in flights)
            {
                bookingRecords = ApplicationData.Connection.GetRecordsByFlightPaidInMoney(flight.FlightId);
                uint sumOfRecords = 0; 
                foreach (BookingRecord record in bookingRecords)
                {
                    // Times 100 because look at definition in BookingRecord.cs
                    sumOfRecords += record.Dollars * 100; 
                }
                income.Add(sumOfRecords); 
            }
            return income; 

        }

        public static void PrintFlightManifest()
        {

        }

        public static void FlightsToOffer()
        {

        }

        public static void AssignPlanes()
        {

        }
        
    }
}
